version: '3'

services:
  mysql:
    build: './mysql'
    restart: 'always' 
    
  apache:
    build: './apache'
    restart: 'always'
    container_name: php_web
    depends_on:
      - mysql
    volumes:
      - ./apache/www/:/var/www/html/
    ports:
      - "80:80"
    stdin_open: true
    tty: true
  php: 
        build: './php'
        restart: 'always'
        volumes:
            - ./public_html:/usr/local/apache2/htdocs